#!/bin/bash
# pixelfed upgrade 1 -> 2

sudo usermod -a -G www-data pixel
(cd /var/www/html &&
 git config --global --add safe.directory /var/www/html &&
 git checkout -- CHANGELOG.md
 git pull origin v0.12.1 &&
 chmod -R 0775 vendor &&
 chmod -R 0775 bootstrap &&
 chmod -R 0775 CHANGELOG.md &&
 chown -R www-data:www-data vendor &&
 chown -R www-data:www-data bootstrap &&
 chown -R www-data:www-data CHANGELOG.md &&
 su - pixel -c "cd /var/www/html && composer install && sudo php artisan config:cache && sudo php artisan route:cache && php artisan migrate --force")

echo 2 > /root/.targetonce
