#!/bin/bash
# ollamaweb upgrade 10 -> 11

(cd /app &&
 git pull &&
 git fetch --tags &&
 git checkout tags/v0.3.1 &&
 npm i &&
 npm run build &&
 cd backend &&
 pip install -r requirements.txt -U &&
 systemctl restart openwebui.service)

echo 11 > /root/.targetonce
