#!/bin/bash
# ollamaweb upgrade 12 -> 13

(cd /app &&
 git pull &&
 git fetch --tags &&
 git checkout tags/v0.3.3 &&
 npm i &&
 npm run build &&
 cd backend &&
 pip install -r requirements.txt -U &&
 systemctl restart openwebui.service)

echo 13 > /root/.targetonce
