#!/bin/bash
# ollamaweb upgrade 13 -> 14

(cd /app &&
 git pull &&
 git fetch --tags &&
 git checkout tags/v0.3.4 &&
 npm i &&
 npm run build &&
 cd backend &&
 pip install -r requirements.txt -U &&
 systemctl restart openwebui.service)

echo 14 > /root/.targetonce
