#!/bin/bash
# ollamaweb upgrade 14 -> 15

(cd /app &&
 git pull &&
 git fetch --tags &&
 git checkout tags/v0.3.5 &&
 npm i &&
 npm run build &&
 cd backend &&
 pip install -r requirements.txt -U &&
 systemctl restart openwebui.service)

echo 15 > /root/.targetonce
