#!/bin/bash
# ollamaweb upgrade 15 -> 16

(cd /app &&
 git pull &&
 git fetch --tags &&
 git checkout tags/v0.3.6 &&
 npm i &&
 npm run build &&
 cd backend &&
 pip install -r requirements.txt -U &&
 systemctl restart openwebui.service)

echo 16 > /root/.targetonce
