#!/bin/bash
# ollamaweb upgrade 16 -> 17

(cd /app &&
 git pull &&
 git fetch --tags &&
 git checkout tags/v0.3.7 &&
 npm i &&
 npm run build &&
 cd backend &&
 pip install -r requirements.txt -U &&
 systemctl restart openwebui.service)

apt-get update -y
apt-get upgrade -y
apt-get clean
rm -rf /var/lib/apt/lists/*

echo 17 > /root/.targetonce
