#!/bin/bash
# ollamaweb upgrade 3 -> 4

(cd /app &&
 git pull &&
 git fetch --tags &&
 git checkout tags/v0.1.125 &&
 npm i &&
 npm run build &&
 cd backend &&
 pip install -r requirements.txt -U &&
 systemctl restart openwebui.service)

echo 4 > /root/.targetonce
