#!/bin/bash
# ollamaweb upgrade 5 -> 6

(cd /app &&
 git pull &&
 git fetch --tags &&
 git checkout tags/v0.2.1 &&
 npm i &&
 npm run build &&
 cd backend &&
 pip install -r requirements.txt -U &&
 systemctl restart openwebui.service)

echo 6 > /root/.targetonce
