#!/bin/bash
# ollamaweb upgrade 6 -> 7

(cd /app &&
 git pull &&
 git fetch --tags &&
 git checkout tags/v0.2.2 &&
 npm i &&
 npm run build &&
 cd backend &&
 pip install -r requirements.txt -U &&
 systemctl restart openwebui.service)

echo 7 > /root/.targetonce
