#!/bin/bash
# ollamaweb upgrade 7 -> 8

(cd /app &&
 git pull &&
 git fetch --tags &&
 git checkout tags/v0.2.3 &&
 npm i &&
 npm run build &&
 cd backend &&
 pip install -r requirements.txt -U &&
 systemctl restart openwebui.service)

echo 8 > /root/.targetonce
