#!/bin/bash
# ollamaweb upgrade 8 -> 9

(cd /app &&
 git pull &&
 git fetch --tags &&
 git checkout tags/v0.2.4 &&
 npm i &&
 npm run build &&
 cd backend &&
 pip install -r requirements.txt -U &&
 systemctl restart openwebui.service)

echo 9 > /root/.targetonce
