#!/bin/bash
# codeserver upgrade 1 -> 2

arch=$(arch | sed s/aarch64/arm64/ | sed s/x86_64/amd64/)

(cd /tmp &&
 curl -fOL https://github.com/coder/code-server/releases/download/v4.89.0/code-server_4.89.0_${arch}.deb &&
 dpkg -i code-server_4.89.0_${arch}.deb &&
 systemctl daemon-reload &&
 systemctl restart code-server@codeserver)

echo 2 > /root/.targetonce
