#!/bin/bash
# codeserver upgrade 5 -> 6

arch=$(arch | sed s/aarch64/arm64/ | sed s/x86_64/amd64/)

(cd /tmp &&
 curl -fOL https://github.com/coder/code-server/releases/download/v4.90.2/code-server_4.90.2_${arch}.deb &&
 dpkg -i code-server_4.90.2_${arch}.deb &&
 systemctl daemon-reload &&
 systemctl restart code-server@codeserver)

echo 6 > /root/.targetonce
