#!/bin/bash
# planka upgrade 6 -> 7

(curl -fsSL https://github.com/plankanban/planka/releases/download/v1.18.1/planka-prebuild-v1.18.1.zip -o /home/planka/planka-prebuild.zip &&
 chown planka:planka /home/planka/planka-prebuild.zip &&
 sudo -u planka bash -c "unzip -o /home/planka/planka-prebuild.zip -d /var/www" &&
 rm /home/planka/planka-prebuild.zip &&
 sudo -u planka bash -c "cd /var/www/planka && npm install" &&
 systemctl restart planka.service)


echo 6 > /root/.targetonce
