#!/bin/bash
# planka upgrade 7 -> 8

(curl -fsSL https://github.com/plankanban/planka/releases/download/v1.19.0/planka-prebuild-v1.19.0.zip -o /home/planka/planka-prebuild.zip &&
 chown planka:planka /home/planka/planka-prebuild.zip &&
 sudo -u planka bash -c "unzip -o /home/planka/planka-prebuild.zip -d /var/www" &&
 rm /home/planka/planka-prebuild.zip &&
 sudo -u planka bash -c "cd /var/www/planka && npm install" &&
 systemctl restart planka.service)


echo 8 > /root/.targetonce
