#!/bin/bash
# gitea upgrade 1 -> 2

systemctl stop gitea
arch=$(arch | sed s/aarch64/arm64/ | sed s/x86_64/amd64/)
wget https://github.com/go-gitea/gitea/releases/download/v1.22.0/gitea-1.22.0-linux-${arch} -O /usr/bin/gitea
systemctl start gitea

echo 2 > /root/.targetonce
